<?php

return [
    'title' => getenv('MYUPLOAD_TITLE','My Upload'),
    'subtitle' => getenv('MYUPLOAD_SUBTITLE','Help us document and preserve history.'),
    'submit_step_text' => getenv('MYUPLOAD_SUBMIT_STEP','We will review your submission and let you know when it is approved.'),
    'wanted_items_text' => getenv('MYUPLOAD_WANTED_ITEMS','We are looking for photographs, documents and audiovisual materials that tell the stories of our community. Our most wanted subjects are:'),
    'copyright_disabled' => getenv('MYUPLOAD_COPYRIGHT_DISABLED',false),
    'thankyou' => getenv('MYUPLOAD_THANKYOU','Your item has been uploaded. You will receive an email when your item is loaded.'),
    'metadata_label' => getenv('MYUPLOAD_METADATA_LABEL', 'Metadata (author, description, etc.)*'),
    'metadata_label_individual' => getenv('MYUPLOAD_METADATA_LABEL_INDIVIDUAL', 'Submit metadata for each item individually'),
    'metadata_label_group' => getenv('MYUPLOAD_METADATA_LABEL_GROUP', 'Submit metadata that will be used for all items'),
    'date_label' => getenv('MYUPLOAD_DATE_LABEL','Original Date'),
    'date_label_sub' => getenv('MYUPLOAD_DATE_LABEL_SUB','When was the item taken or created?'),
    'location_label' => getenv('MYUPLOAD_LOCATION_LABEL','Original Location'),
    'location_label_sub' => getenv('MYUPLOAD_LOCATION_LABEL_SUB','Address and city if possible.'),
    'author_label' => getenv('MYUPLOAD_AUTHOR_LABEL','Author/Creator*'),
    'author_label_sub' => getenv('MYUPLOAD_AUTHOR_LABEL_SUB','Who took the photo or wrote the document?'),
    'description_label' => getenv('MYUPLOAD_DESCRIPTION_LABEL','Description*'),
    'description_label_sub' => getenv('MYUPLOAD_DESCRIPTION_LABEL_SUB','What is this item and why is it important?'),
    'credit_disabled' => getenv('MYUPLOAD_CREDIT_DISABLED',0),
    'credit_label' => getenv('MYUPLOAD_CREDIT_LABEL','Credit*'),
    'credit_label_sub' => getenv('MYUPLOAD_CREDIT_LABEL_SUB','How would you like your name to appear on MyUpload?'),
    'author_not_required' => getenv('MYUPLOAD_AUTHOR_NOT_REQUIRED',0),
    'approval_emails_disabled' => getenv('MYUPLOAD_APPROVAL_EMAILS_DISABLED',false),
];
